asr_service:
  device: cuda:0
  max_retries: 1
  model_path: /models/asr/streaming
  provider: funasr
  timeout: 3.0
audio_processing:
  bit_depth: 16
  channels: 1
  enable_vad: true
  format: wav
  sample_rate: 16000
  vad_model: silero
latency_optimization:
  hardware_optimization:
    gpu_memory_fraction: 0.8
    mixed_precision: true
    tensorrt_optimization: true
    use_gpu: true
  model_settings:
    chunk_size: 80
    model_type: streaming
    overlap_size: 40
    partial_results: true
    silence_timeout: 0.3
    vad_threshold: 0.2
  system_optimization:
    cpu_affinity:
    - 0
    - 1
    - 2
    - 3
    disable_swap: true
    high_priority: true
    memory_lock: true
performance_settings:
  connection_pool_size: 50
  io_threads: 8
  max_concurrent_requests: 200
  request_queue_size: 500
  worker_threads: 16
