global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'xiaozhi-server'
    static_configs:
      - targets: ['xiaozhi-esp32-server-optimized:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['xiaozhi-esp32-server-redis-optimized:6379']

  - job_name: 'mysql'
    static_configs:
      - targets: ['xiaozhi-esp32-server-db-optimized:3306']