apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-service
  namespace: xiaozhi-system
  labels:
    app: asr-service
    component: ai-pipeline
spec:
  replicas: 8
  selector:
    matchLabels:
      app: asr-service
  template:
    metadata:
      labels:
        app: asr-service
        component: ai-pipeline
    spec:
      containers:
      - name: asr-service
        image: xiaozhi/asr-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_MAX_CONNECTIONS
          value: "50"
        - name: BATCH_SIZE
          value: "16"
        - name: MAX_CONCURRENT
          value: "32"
        - name: MODEL_PATH
          value: "/models/SenseVoiceSmall"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: MODEL_PRECISION
          value: "fp16"
        - name: CPU_THREADS
          value: "4"
        resources:
          requests:
            cpu: 1500m
            memory: 6Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 3000m
            memory: 12Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - name: model-storage
          mountPath: /models
        - name: tmp-storage
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /asr/stats
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /asr/stats
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
      - name: tmp-storage
        emptyDir:
          sizeLimit: 2Gi
      nodeSelector:
        accelerator: nvidia-tesla-t4
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: asr-service
  namespace: xiaozhi-system
  labels:
    app: asr-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: asr-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asr-service-hpa
  namespace: xiaozhi-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asr-service
  minReplicas: 3
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120