apiVersion: apps/v1
kind: Deployment
metadata:
  name: vad-service
  namespace: xiaozhi-system
  labels:
    app: vad-service
    component: ai-pipeline
spec:
  replicas: 6  # 从3增加到6，提升并发处理能力
  selector:
    matchLabels:
      app: vad-service
  template:
    metadata:
      labels:
        app: vad-service
        component: ai-pipeline
    spec:
      containers:
      - name: vad-service
        image: xiaozhi/vad-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: BATCH_SIZE
          value: "32"  # 从8增加到32，匹配代码优化
        - name: MAX_CONCURRENT
          value: "48"  # 从16增加到48，匹配代码优化
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_MAX_CONNECTIONS
          value: "50"
        - name: MODEL_PATH
          value: "/models/silero_vad"
        resources:
          requests:
            cpu: 1000m   # 从500m增加到1000m
            memory: 2Gi  # 从1Gi增加到2Gi
          limits:
            cpu: 2000m   # 从1000m增加到2000m
            memory: 4Gi  # 从2Gi增加到4Gi
        volumeMounts:
        - name: model-storage
          mountPath: /models
        livenessProbe:
          httpGet:
            path: /vad/stats
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /vad/stats
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vad-service
  namespace: xiaozhi-system
  labels:
    app: vad-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: vad-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vad-service-hpa
  namespace: xiaozhi-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vad-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60